/* Autogenerated with kurento-module-creator */

#ifndef __RECORDER_MODULE_IMPL_HPP__
#define __RECORDER_MODULE_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "RecorderModule.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "RecorderModuleOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace recordermodule
{
class RecorderModuleImpl;
} /* recordermodule */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::recordermodule::RecorderModuleImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace recordermodule
{

class RecorderModuleImpl : public OpenCVFilterImpl, public virtual RecorderModule, public virtual RecorderModuleOpenCVImpl
{

public:

  RecorderModuleImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline, const std::string &path, const std::string &filename);

  virtual ~RecorderModuleImpl() = default;

  virtual std::string getPath ();
  virtual void setPath (const std::string &path);

  virtual std::string getFilename ();
  virtual void setFilename (const std::string &filename);

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* recordermodule */
} /* module */
} /* kurento */

#endif /*  __RECORDER_MODULE_IMPL_HPP__ */
